### ISSUE TITLE
Add limit to number of chances given to the player

### ISSUE THREAD

**Issue by harshit-sharma-gits** [aastha-chauhan-gits/Number_Guessing_Game_Python#1]
As the title describes, the program should put up a limit to the number of chance a player can take (say 10) to guess the number

**Comment by harshit-sharma-gits** [comment]
And, of course, if the player is not able to guess the number in given chances, then it is going to be a failed attempt

**Comment by harshit-sharma-gits** [comment]
This leads to a future perspective of the app, to add the rankings to it, that is, giving ranks to the players and show the leaderboard also

We can have a separate issue, and a detailed discussing on it later on!

**Comment by aastha-chauhan-gits** [comment]
Thanks for your suggestion! I added the limit on the number of attempts a player can take.

**Comment by harshit-sharma-gits** [comment]
Great! c185d108965589eb0f71771e8a19980674437d95 this commit, tested positive!
